# Generated by Django 2.2 on 2021-04-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_dojo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='amount_of_ninjas',
            field=models.IntegerField(default=0),
        ),
    ]
